#    pre-commit run --all-files
#    https://pre-commit.com
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: master
      hooks:
        - id: check-json
        - id: pretty-format-json
          args: [--autofix, --no-sort-keys]
  -   repo: https://github.com/dnephin/pre-commit-golang
      rev: master
      hooks:
        - id: go-fmt
        - id: go-unit-tests
